# Generated by Django 2.0.1 on 2018-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='to_review',
            field=models.BooleanField(default=False),
        ),
    ]
