# Generated by Django 2.0.7 on 2018-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userprofile_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='submission_karma',
            field=models.IntegerField(default=0),
        ),
    ]
