# Generated by Django 2.0.1 on 2018-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
