# Generated by Django 2.0.2 on 2018-02-15 18:24

from django.db import migrations

def create_default_room_subscriptions(apps, schema_editor):
    Topic = apps.get_model('mainapp', 'Topic')
    Subscription = apps.get_model('mainapp', 'Subscription')
    User = apps.get_model('auth', 'User')

    default_topics = ['general' ,'bitcoin', 'ethereum', 'programming', 'cryptocurrency']

    for topic_name in default_topics:
        if Topic.objects.filter(name=topic_name).exists():
            topic = Topic.objects.get(name=topic_name)
        else:
            topic = Topic(name=topic_name, title=topic_name)
            topic.save()
        for user in User.objects.all():
            if Subscription.objects.filter(user=user, topic=topic).exists():
                continue
            subscription = Subscription(user=user, topic=topic)
            subscription.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180213_0942'),
    ]

    operations = [
        migrations.RunPython(create_default_room_subscriptions),
    ]
