# Generated by Django 2.1.2 on 2018-10-18 12:36

from django.db import migrations

def create_default_rooms(apps, schema_editor):
    Topic = apps.get_model('mainapp', 'Topic')
    Room = apps.get_model('mainapp', 'Room')
    ChatMessage = apps.get_model('mainapp', 'ChatMessage')

    #create general and off-topic rooms for every topic

    for topic in Topic.objects.all():
        if Room.objects.filter(name="general", topic=topic).exists():
            continue
        room_general = Room(name="general", topic=topic)
        room_general.save()
    
    for topic in Topic.objects.all():
        if Room.objects.filter(name="off-topic", topic=topic).exists():
            continue
        room_offtopic = Room(name="off-topic", topic=topic)
        room_offtopic.save()
    
    #set the default room to general for all chat messages

    for chat_message in ChatMessage.objects.all():
        if chat_message.room is None:
            room_general = Room.objects.get(topic=chat_message.topic, name="general")
            chat_message.room = room_general
            chat_message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20181018_1149'),
    ]

    operations = [
        migrations.RunPython(create_default_rooms),
    ]
