# Generated by Django 2.1.2 on 2018-10-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20181018_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='position',
            field=models.IntegerField(default=10),
        ),
    ]
